# Numpy Array Operations

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [69]:
# List of functions explained 
function1 = np.linspace  
function2 = np.reshape
function3 = np.vstack
function4 = np.unique
function5 = np.append

## Function 1 - np.linspace
np.linspace function returns evenly spaced numbers over a specified interval.

Returns specified number of evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

### Syntax:
*numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)*
#### Parameters:
**start**  : [optional] start of interval range. By default start = 0

**stop**   : end of interval range

**restep** : If True, return (samples, step). By deflut restep = False

**num**    : [int, optional] No. of samples to generate

**dtype**  : type of output array

In [11]:
# Example 1 

arr1 = np.linspace(start=1, stop=9, num=9, dtype=int)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In the above example, created an array of 9 evenly spaced elements of type integer.

In [12]:
# Example 2 

arr2 = np.linspace(start=3, stop=12, num=9, endpoint=False)
print(arr2)

[ 3.  4.  5.  6.  7.  8.  9. 10. 11.]


In the above example, created an array of 9 evenly spaced elements of type float with excluding the upper edge limit.

In [16]:
# Example 3

arr3 = np.linspace(start=10, num=20)
arr3

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In the above example, tried to create an array with the help of np.linspace function. As I failed to specify the end point, it has thrown an error.

The linspace() function is used in situations where we require to generate arrays with evenly spaced elements.

## Function 2 - np.reshape
np.reshape function gives a new shape to an array without changing its data.

### Syntax:
*numpy.reshape(array, shape, order='C')*

#### Parameters:
**array** : [array_like]Input array

**shape** : [int or tuples of int] e.g. if we are aranging an array with 10 elements then shaping
        it like numpy.reshape(4, 8) is wrong
        
**order**  : [C-contiguous, F-contiguous, A-contiguous; optional] 

Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.



In [21]:
# Example 1

arr1 = [1,2,3,4,5,6,7,8,9]
arr1 = np.reshape(arr1, (3,3), order='C')
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In the above example, reshaped a 1_D array to a 2_D array of size 3x3 with order='C' which reshapes the elements row wise.

In [22]:
# Example 2

arr2 = [1,2,3,4,5,6,7,8,9]
arr2 = np.reshape(arr2, (3,3), order='F')
print(arr2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In the above example, reshaped a 1_D array to a 2_D array of size 3x3 with order='F' which reshapes the elements column wise.

In [23]:
# Example 3

arr3 = [1,2,3,4,5,6,7,8,9]
arr3 = np.reshape(arr3, (3,2))
print(arr3)

ValueError: cannot reshape array of size 9 into shape (3,2)

In the above example, tried to reshape an array with 9 elements into shape (3,2) which can not be done.

 The criterion to satisfy for providing the new shape is that 'The new shape should be compatible with the original shape'. numpy allow us to give one of new This is, when reshaping the total number of elements must be the same, so adding -1 to the shape just lets numpy calculate the remaining value for you, so that the product of the axes still matches the previous number of elements

## Function 3 - np.vstack

numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.

This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N). Rebuilds arrays divided by vsplit.

### Syntax:
*numpy.vstack(tup)*

#### Parameters:
**tup** : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the first axis.

**Return** : [stacked ndarray] The stacked array of the input arrays.

In [27]:
# Example 1 

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])

arr3 = np.vstack((arr1, arr2))
print(arr3)

[[1 2 3]
 [2 3 4]]


In the above example, using np.vstack function, we stacked two 1-D arrays vertically.

In [31]:
# Example 2

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[2, 3, 4], [5, 6, 7]])

arr3 = np.vstack((arr1, arr2))
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]
 [5 6 7]]


In the above example, using np.vstack function, we stacked two 2-D arrays vertically. Here one thing should be noticed that the dimensions along the first axis are not matching.

In [30]:
# Example 3 

arr1 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
arr2 = np.array([[2, 3, 4], [5, 6, 7]])

arr3 = np.vstack((arr1, arr2))
print(arr3)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In the above example, we tried to stack two arrays with different dimensions. All the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

numpy.vstack () is a function that helps to stack the input array sequence vertically in order to create a single array. The arrangement will be in row-wise. It is similar to concatenation along the axis 1 after 1-Dimensional arrays of (N) shape have been reshaped to the format (1,N).

## Function 4 - np.unique

The numpy.unique() function finds the unique elements of an array and returns these unique elements as a sorted array.

Apart from the unique elements, there are some optional outputs also, which are as follows:
* The output can be the indices of the input array which give the unique values
* The output can be the indices of the unique array which reconstruct the input array
* The output can be an array of the number of times each unique value comes in the input array.

### Syntax:
*numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)*
#### Parameters:
**ar**: array_like
Input array. Unless axis is specified, this will be flattened if it is not already 1-D.

**return_index**: bool, optional
If True, also return the indices of ar (along the specified axis, if provided, or in the flattened array) that result in the unique array.

**return_inverse**: bool, optional
If True, also return the indices of the unique array (for the specified axis, if provided) that can be used to reconstruct ar.

**return_counts**: bool, optional
If True, also return the number of times each unique item appears in ar.

**axis**: int or None, optional
The axis to operate on. If None, ar will be flattened. If an integer, the subarrays indexed by the given axis will be flattened and treated as the elements of a 1-D array with the dimension of the given axis, see the notes for more details. Object arrays or structured arrays that contain objects are not supported if the axis kwarg is used. The default is None.

In [45]:
# Example 1 

arr1 = np.array([[1, 1, 0], 
                 [1, 1, 0], 
                 [2, 3, 4], 
                 [5, 9, 8], 
                 [2, 3, 4]])  
arr2 = np.unique(arr1)  

print('arr1:\n', arr1) 
print('arr2:\n', arr2)


arr1:
 [[1 1 0]
 [1 1 0]
 [2 3 4]
 [5 9 8]
 [2 3 4]]
arr2:
 [0 1 2 3 4 5 8 9]


In the above example, an array has been generated that contains unique elements of the input array.

In [46]:
# Example 2 

arr1 = np.array([[1, 1, 0], 
                 [1, 1, 0], 
                 [2, 3, 4], 
                 [5, 9, 8], 
                 [2, 3, 4]])  
arr2 = np.unique(arr1, axis=0)  

print('arr1:\n', arr1) 
print('arr2:\n', arr2)

arr1:
 [[1 1 0]
 [1 1 0]
 [2 3 4]
 [5 9 8]
 [2 3 4]]
arr2:
 [[1 1 0]
 [2 3 4]
 [5 9 8]]


In the above example, an array has been generated that contains unique rows of the input array.

In [59]:
# Example 3 

a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=2)


AxisError: axis 2 is out of bounds for array of dimension 2

In the above example, tried to find the unique values along the second axis which doesn't exist. Axis 2 is out of bounds for an array of dimension 2.

np.unique function returns an array of unique elements in the input array. The function can be able to return a tuple of array of unique vales and an array of associated indices. Nature of the indices depend upon the type of return parameter in the function call.

## Function 5 - np.append

The numpy.append() appends values along the mentioned axis at the end of the array

### Syntax:
*numpy.append(array, values, axis = None)*

#### Parameters:
**array**   : [array_like]Input array. 

**values**  : [array_like]values to be added in the arr. Values should be 
     shaped so that arr[...,obj,...] = values. If the axis is defined values can be of any
     shape as it will be flattened before use.

**axis**    : Axis along which we want to insert the values. By default, array
     is flattened. 

In [61]:
# Example 1

arr1 = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In the above example, using np.append we have added the elements at the end of the array along the 0th axis.

In [66]:
# Example 2 

arr1 = np.append([[1, 2, 3], [4, 5, 6, ]], [[7, 8, 9], [0, 1, 2]], axis=1)
print(arr1)

[[1 2 3 7 8 9]
 [4 5 6 0 1 2]]


In the above example, we have added the elements at the end of the array along the first axis.

In [63]:
# Example 3 

arr1 = []
arr1 = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=1)
print(arr1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In the above example, we tried to append the elements, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1. All the input array dimensions for the concatenation axis must match exactly.

Two arrays in python can be appended in multiple ways using np.append function.

## Conclusion

In this notebook we have discussed some important numpy array funtions and their applications. Also we have seen the failing conditions of these functions. There are a lot more cool functions to learn in numpy library. Feel free to visit the following links to learn more about numpy array functions.

## Reference Links
References and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy array tutorial by datacamp: https://www.datacamp.com/community/tutorials/python-numpy-tutorial
* Numpy tutorial by tutorialspoint: https://www.tutorialspoint.com/numpy/index.htm